#
### Configuration file for Foundation Directory scraper script, fd_scrape.py
#
# Must have FD 'Professional' subscription with valid username and password.
# Subscribe at https://fconline.foundationcenter.org/
#
username: lindsey@legupdata.com
password: 1Foundation23;
#
login_url: https://fconline.foundationcenter.org/login
#
# The target_url and page_url here are the basic queries that return all results for a given ein
# These versions Limit query to all grants for a given EIN with subject areas 'Graduate and Professional Education' and 'Higher education'
target_url: https://fconline.foundationcenter.org/fdo-search/search/?collection=grants&activity=form&_new_search=1&quicksearch=american+petroleum+institute&subject_match=match_any&subject_area=SB06%2CSB05&population_match=match_any&government_grantmaker=1&amount_min=%240&amount_max=%2410%2C000%2C000%2C000&year_min=2003&year_max=2025&view_all=1
page_url: https://fconline.foundationcenter.org/fdo-search/search/?collection=grants&activity=form&quicksearch=american+petroleum+institute&subject_match=match_any&subject_area=SB06%2CSB05&population_match=match_any&government_grantmaker=1&amount_min=%240&amount_max=%2410%2C000%2C000%2C000&year_min=2003&year_max=2025&view_all=1
#
# additional info about refining funcitonality using the target_url and page_url:
# To change what is searched for, use the foundation directory search interface, put a single EIN
# in the 'EIN' search box (in 'Advanced Search & Filters' and 'Additional Filters'), then
# set the parameters/filters you like, press 'search', and copy the https:// address
# from the browswer search bar. To ensure the scraping script works effectively, make sure
# to remove both '&ein=[YOUR EIN HERE]' and '&page=[pagenumber]' from the end of the https:// address string
# output details
suffix: _grants.csv
more_than_100: big_eins_with_more_than_100_pages.yml. # name of file that records eins with more than 100 pages of results
no_grants_for_ein: big_eins_without_grants.yml # name of file that records eins without any results for these queries
wait_seconds: 60
number_captchas: 1 # if there are more than 1 captcha to handle, increase this count for the human interaction
eins:
 - aes : '820657376'
 - aes : '873898365'
 - accuracy_in_media : '237135837'
 - adolph_coors_foundation : '510172279'
 - air_liquide : '760366343'
 - air_liquide : '760683589'
 - alabama_power : '570901832'
 - allegheny_institute_for_public_policy : '251704173'
 - alliant : '391444065'
 - ameren : '436022693'
 - american_airlines : '752855813'
 - american_airlines : '762086656'
 - american_conservation_coalition : '823815628'
 - american_conservative_union_foundation : '521294680'
 - american_constitutional_rights_union : '522121856'
 - american_council_for_capital_formation : '521091172'
 - american_electric_power : '237418083'
 - american_electric_power : '203886453'
 - american_enterprise_institute_for_public_policy_research : '530218495'
 - american_fuel_and_petrochemical_manufacturers : '530115970'
 - american_gas_association : '130431590'
 - american_legislative_exchange_council : '520140979'
 - american_petroleum_institute : '130433430'
 - american_spectator_foundation : '237002632'
 - americans_for_prosperity : '521527294'
 - anglo_american : '432031982'
 - annenberg_foundation : '236257083'
 - anschutz : '742316617'
 - anschutz : '742132676'
 - antero : '831090369'
 - antero : '841570723'
 - arcelormittal : '352121803'
 - arch_coal : '203980901'
 - atlas_economic_research_foundation_atlas : '942763845'
 - basf : '562312894'
 - bhp : '611714573'
 - bp : '366046879'
 - berkshire_hathaway_energy : '473577741'
 - beth_and_ravenel_curry_foundation : '237411083'
 - black_hills_corporation : '752986866'
 - blackstone : '260462996'
 - boeing_company_charitable_trust : '916056738'
 - cms_energy : '383575175'
 - cnx : '872046299'
 - consol : '841776958'
 - crh : '222669586'
 - calpine : '260025038'
 - cascade_policy_institute : '931045925'
 - caterpillar : '376022314'
 - cato_institute : '237432162'
 - cemex : '346505254'
 - center_for_american_and_international_law : '756012849'
 - center_for_defense_of_free_enterprise : '910973976'
 - center_for_security_policy_inc : '521601976'
 - center_for_strategic_and_international_studies : '521501082'
 - center_of_the_american_experiment : '363611426'
 - centerpoint_energy : '351950691'
 - charles_koch_foundation : '854058882'
 - charles_koch_foundation : '480918408'
 - charles_koch_institute : '274967732'
 - cheniere : '822691447'
 - chevron : '133007516'
 - citizens_for_affordable_energy_inc : '263060991'
 - co2_coalition : '473722575'
 - coalition_for_american_jobs : '275075681'
 - competitive_enterprise_institute : '521351785'
 - consumers_energy : '382935534'
 - continental_resources : '465605197'
 - cummins : '356042373'
 - dte_energy : '382708636'
 - daniels_fund : '841393308'
 - david_h_koch_charitable_foundation : '480926946'
 - delta_air_lines : '586073119'
 - devon_energy : '365040938'
 - discovery_institute : '911521697'
 - domestic_energy_producers_alliance : '264396861'
 - dominion_energy : '472746460'
 - dominion_energy : '570784136'
 - donlin_gold : '371850899'
 - donors_capital_fund : '541934032'
 - donors_trust : '522166327'
 - dow : '381437485'
 - dow : '386058512'
 - dow : '382314603'
 - duke_energy : '581586283'
 - dunn_foundation : '650415977'
 - eqt : '043747289'
 - eagle_forum : '823851756'
 - edison_electric_institute : '130659550'
 - encana : '205064193'
 - energy_transfer : '203459268'
 - enlink : '203523983'
 - entergy : '710845366'
 - exelon : '830499473'
 - exxonmobil : '136082357'
 - firstenergy : '346514181'
 - fraser_institute : '980032427'
 - frontiers_of_freedom_institute : '863001793'
 - future_of_freedom_foundation : '742543375'
 - ge_vernova : '932481739'
 - general_motors : '382132136'
 - georgia_power : '581709417'
 - heartland_institute : '363309812'
 - heritage_foundation : '237327730'
 - herrick_foundation : '386041517'
 - hertog_foundation : '262002295'
 - hess : '921406835'
 - hess : '221713046'
 - honda : '311006130'
 - honda : '813059710'
 - honda : '953924667'
 - howard_charitable_foundation : '911952040'
 - hudson_institute : '131945157'
 - itochu : '845135131'
 - idaho_power : '820530529'
 - illinois_policy_institute : '412057028'
 - independence_institute : '840990300'
 - independent_institute : '943008370'
 - independent_petroleum_association_of_america : '730296927'
 - independent_womens_forum : '541670627'
 - industrial_energy_consumers_of_america : '222466569'
 - institute_for_energy_research : '760149778'
 - institute_for_liberty : '030231818'
 - institute_for_regulatory_science : '541352139'
 - institute_for_policy_innovation : '752158093'
 - international_policy_network : '522363626'
 - james_madison_institute_for_public_policy_studies : '592811908'
 - john_locke_foundation_inc : '561656943'
 - john_templeton_foundation : '621322826'
 - john_william_pope_foundation : '581691765'
 - kern_family_foundation : '391923558'
 - kiewit : '476098282'
 - kiewit : '476029996'
 - kinder_morgan : '841148161'
 - knowledge_and_progress_fund : '541899251'
 - koch_family : '486113560'
 - lakeside_foundation : '946066229'
 - lexington_institute : '541880642'
 - lillian_s._wells_foundation : '237433827'
 - lilly_endowment : '350868122'
 - locke_institute : '541556624'
 - lockheed : '136161566'
 - lynde_and_harry_bradley_foundation : '396037928'
 - mackinac_center : '382701547'
 - manhattan_institute_for_policy_research_inc : '132912529'
 - marathon_petroleum : '464439930'
 - media_research_center_inc : '541429009'
 - mercatus_center : '541436224'
 - mercer_family_foundation : '201982204'
 - midamerican_energy : '421338550'
 - minnesota_power : '562560595'
 - mitsubishi : '521700855'
 - mitsubishi : '383735804'
 - mitsubishi : '330773994'
 - mitsubishi_corporation : '133676166'
 - mitsui : '133415220'
 - murphy_oil : '874000291'
 - nrg : '273283754'
 - national_fuel_gas : '201860605'
 - national_grid : '113466416'
 - national_mining_association : '521916480'
 - national_petroleum_council : '530182304'
 - national_philanthropic_trust : '237825575'
 - national_rural_electric_cooperative_association : '530116145'
 - national_taxpayers_union : '521122683'
 - nebraska_public_power : '453689549'
 - nestle : '956027479'
 - nestle : '956118622'
 - nestle : '873568395'
 - nextera : '650031452'
 - nisource : '510324200'
 - nissan : '954413799'
 - noble_research_institute : '730606209'
 - oge_energy : '736093572'
 - oneok : '731503823'
 - ohio_oil : '311055701'
 - ohio_oil : '314363514'
 - oklahoma_council_of_public_affairs : '731436375'
 - oregon_institute_of_science_and_medicine : '930814898'
 - ovintiv : '760663978'
 - ppl : '461605118'
 - pacificorp : '943089826'
 - pacific_research_institute_for_public_policy : '942528433'
 - panasonic : '222548639'
 - pharmaceutical_research_and_manufacturers_of_america : '526063009'
 - pioneer_natural_resources : '752443728'
 - prometheus_foundation : '271456655'
 - ramaco : '882516783'
 - reason_foundation : '953298239'
 - rhode_island_center_for_freedom_and_prosperity : '452805369'
 - richard_and_barbara_gaby_foundation : '202110682'
 - richard_and_helen_devos_foundation : '456659303'
 - roberts_foundation : '942967074'
 - roe_foundation : '237011541'
 - ssab : '201173879'
 - ssab : '412191056'
 - swepco : '261318214'
 - sarah_scaife_foundation : '251113452'
 - schwab_charitable : '261997839'
 - searle_freedom_trust : '367244615'
 - sempra : '261325469'
 - shelby_cullom_davis_charitable_fund : '203734688'
 - shell_usa : '136066583'
 - smith_richardson_foundation : '560611550'
 - south_carolina_policy_council : '570835744'
 - southern_company : '582514027'
 - southern_company : '582399946'
 - sumitomo : '202103634'
 - tc_energy : '473504335'
 - texas_public_policy_foundation : '742524057'
 - thomas_w_smith_foundation : '473862135'
 - toyota : '300150685'
 - toyota : '364479457'
 - toyota : '953255038'
 - truth_in_accounting : '352185292'
 - unilever : '136122117'
 - united_airlines : '853565514'
 - united_airlines : '760691086'
 - valero_energy : '742904514'
 - vanguard_charitable : '232888152'
 - volkswagen : '521690493'
 - walton_family_foundation : '133441466'
 - western_energy_alliance : '840700841'
 - william_k._bowes,_jr._foundation : '943148482'
 - williams_companies : '237413843'
 - wisconsin_public_service : '396075016'
 - xcel_energy : '412007734'
 - ypf : '832628573'
 - the_southern_company: '854309897'
 - diana_davis_spencer_foundation: '203672969'
 - m.j._murdock_charitable_trust: '237456468'
 - william_e._simon_foundation,_inc.: '136217788'
 - communications_institute: '200159213'
 - freedomworks_foundation: '521526916'
 - equitrans_midstream_corporation: '832213567'
 - norfolk_southern: '521328375'
 - union_pacific: '136406825'
 - acton_institute_for_the_study_of_religion_and_liberty: '382926822'
 - alaska_policy_forum: '264380206'
 - american_association_of_petroleum_geologists: '731298684'
 - american_association_of_petroleum_geologists: '742408556'
 - american_association_of_petroleum_geologists: '730125920'
 - american_coal_council: '840912828'
 - american_exploration_&_production_council: '521042125'
 - caesar_rodney_institute: '262176691'
 - center_for_freedom_and_prosperity_foundation: '542009193'
 - commonwealth_foundation: '232473845'
 - daily_caller_news_foundation_the: '452922471'
 - ethan_allen_institute: '223092292'
 - independent_petroleum_association_of_new_mexico: '850267696'
 - lignite_energy_council: '450321174'
 - nevada_policy_research_institute: '880276314'
 - ohio_oil_&_gas_association: '463106178'
 - oklahoma_energy_education_foundation: '204707442'
 - prageru_(prager_university): '271763901'
 - pulp_and_paperworkers'_resource_council: '202745037'
 - taxpayers_protection_alliance: '812132166'
 - west_virginia_coal_association: '550307050'
 - western_states_petroleum_association: '950596680'
 - young_americans_for_liberty: '453503672'
 - apache_corporation: '416031039'
 - united_airlines: '366109873'
 - anadarko: '262113030'
 - agl: '650098771'
