#
### Configuration file for Foundation Directory scraper script, fd_scrape.py
#
# Must have FD 'Professional' subscription with valid username and password.
# Subscribe at https://fconline.foundationcenter.org/
#
username: lindsey@legupdata.com
password: 1Foundation23;
#
login_url: https://fconline.foundationcenter.org/login
#
# The target_url and page_url here are the basic queries that return all results for a given ein
# These versions Limit query to all grants for a given EIN with subject areas 'Graduate and Professional Education' and 'Higher education'
target_url: https://fconline.foundationcenter.org/fdo-search/search/?collection=grants&activity=form&_new_search=1&quicksearch=american+petroleum+institute&subject_match=match_any&subject_area=SB06%2CSB05&population_match=match_any&government_grantmaker=1&amount_min=%240&amount_max=%2410%2C000%2C000%2C000&year_min=2003&year_max=2025&view_all=1
page_url: https://fconline.foundationcenter.org/fdo-search/search/?collection=grants&activity=form&quicksearch=american+petroleum+institute&subject_match=match_any&subject_area=SB06%2CSB05&population_match=match_any&government_grantmaker=1&amount_min=%240&amount_max=%2410%2C000%2C000%2C000&year_min=2003&year_max=2025&view_all=1
#
# additional info about refining funcitonality using the target_url and page_url:
# To change what is searched for, use the foundation directory search interface, put a single EIN
# in the 'EIN' search box (in 'Advanced Search & Filters' and 'Additional Filters'), then
# set the parameters/filters you like, press 'search', and copy the https:// address
# from the browswer search bar. To ensure the scraping script works effectively, make sure
# to remove both '&ein=[YOUR EIN HERE]' and '&page=[pagenumber]' from the end of the https:// address string
# output details
suffix: _grants.csv
more_than_100: big_eins_with_more_than_100_pages.yml. # name of file that records eins with more than 100 pages of results
no_grants_for_ein: big_eins_without_grants.yml # name of file that records eins without any results for these queries
wait_seconds: 60
number_captchas: 1 # if there are more than 1 captcha to handle, increase this count for the human interaction
eins:
#- ALLETE (Minnesota Power): '562560595'
#- Accuracy In Media: '237135837'
#- Adolph Coors Foundation: '510172279'
#- Alabama Power Co: '570901832'
#- Alliant Energy Corp: '391444065'
#- Ameren Corp: '436022693'
#- American Airlines: '752855813'
#- American Airlines Group Inc.: '762086656'
#- American Conservative Union Foundation: '521294680'
#- American Council For Capital Formation: '521091172'
#- American Electric Power Company Inc (AEP): '203886453'
#- American Electric Power Company Inc (AEP): '237418083'
#- American Enterprise Institute For Public Policy Research: '530218495'
#- American Fuel And Petrochemical Manufacturers: '530115970'
#- American Gas Association: '130431590'
#- American Legislative Exchange Council: '520140979'
#- American Petroleum Institute: '130433430'
#- American Spectator Foundation: '237002632'
#- Americans For Prosperity: '521527294'
#- Anglo American: '432031982'
#- Annenberg Foundation: '236257083'
#- Antero Resources Corporation: '831090369'
#- Antero Resources Corporation: '841570723'
#- ArcelorMittal S.A.: '352121803'
#- Atlas Economic Research Foundation Atlas: '942763845'
#- BASF SE: '562312894'
#- BHP Group: '611714573'
#- BP plc: '366046879'
#- Berkshire Hathaway Energy Company: '473577741'
#- Beth And Ravenel Curry Foundation: '237411083'
#- Black Hills Corporation: '752986866'
#- Blackstone Inc: '260462996'
#- Boeing Company: '431554300'
#- Boeing Company: '916056738'
#- Brady Education Foundation, Inc.: '922466423'
#- CMS Energy Corp: '383575175'
#- CNX Resources Corporation: '872046299'
#- CONSOL Marine Terminals LLC: '841776958'
#- Calpine Corporation: '260025038'
#- Cascade Policy Institute: '931045925'
#- Caterpillar Inc.: '376022314'
#- Cato Institute: '237432162'
#- Cemex SAB de CV: '346505254'
#- Center For American And International Law: '756012849'
#- Center For Defense Of Free Enterprise: '910973976'
#- Center For Security Policy Inc: '521601976'
#- Center For Strategic And International Studies: '521501082'
#- CenterPoint Energy Inc: '351950691'
#- Charles Koch Foundation: '854058882'
#- Charles Koch Foundation: '480918408'
#- Charles Koch Institute: '274967732'
#- Cheniere Energy Inc: '822691447'
#- Citizens For Affordable Energy Inc: '263060991'
#- Coalition For American Jobs: '275075681'
#- Communications Institute: '200159213'
#- Competitive Enterprise Institute: '521351785'
#- Consumers Energy Co: '382935534'
#- Consumers Power Co Financing I: '931095944'
#- Continental Resources Inc: '465605197'
#- Cummins Inc.: '356042373'
#- DTE Energy Co: '382708636'
#- Daniels Fund: '841393308'
#- Danone S.A.: '133889717'
#- David H. Koch Charitable Foundation: '480926946'
#- Delta Air Lines, Inc.: '586073119'
#- Devon Energy Corporation: '365040938'
#- Diana Davis Spencer Foundation: '203672969'
#- Dominion Energy South Carolina Inc: '570784136'
#- Dominion Energy South Carolina Inc: '472746460'
#- Donlin Gold LLC: '371850899'
#- Donors Capital Fund: '541934032'
#- Donors Trust: '262515785'
#- Donors Trust: '522166327'
#- Dow Inc: '386058513'
#- Dow Inc: '382314603'
#- Dow Inc: '382852321'
#- Dow Inc: '381437485'
#- Duke Energy Corporation: '581586283'
#- Dunn Foundation The: '650415977'
#- EQT Corporation: '43747289'
#- Edison Electric Institute: '130659550'
#- Energy Transfer LP: '203459268'
#- Enlink Midstream LLC: '203523983'
#- Entergy Corporation: '710845366'
#- Environmental Conservation Organization: '262933956'
#- Equitrans Midstream Corporation: '832213567'
#- Exelon Corp.: '830499473'
#- Exxon Mobil Corporation: '136082357'
#- FirstEnergy Corp: '346514181'
#- Fraser Institute: '980032427'
#- Freedom Action: '821530064'
#- Freedomworks Foundation: '521526916'
#- Frontiers Of Freedom Institute Inc: '863001793'
#- GE Vernova (former General Electric Co.): '932481739'
#- Georgia Power Co: '581709417'
#- Heartland Institute: '363309812'
#- Heritage Foundation: '237327730'
#- Herrick Foundation: '386041517'
#- Hertog Foundation: '262002295'
#- Hess Corporation: '455480925'
#- Hess Corporation: '550751425'
#- Hess Corporation: '221713046'
#- Hess Corporation: '921406835'
#- Honda Motor Co., Ltd.: '311006130'
#- Honda Motor Co., Ltd.: '813059710'
#- Honda Motor Co., Ltd.: '953924667'
#- Howard Charitable Foundation: '911952040'
#- Hudson Institute: '131945157'
#- Idaho Power Co: '820530529'
#- Illinois Policy Institute: '412057028'
#- Independence Institute: '840990300'
#- Independent Institute: '943008370'
#- Independent Petroleum Association Of America: '730296927'
#- Independent Womens Forum: '541670627'
#- Industrial Energy Consumers Of America: '222466569'
#- Institute For Energy Research: '760149778'
#- Institute For Liberty: '30231818'
#- Institute For Regulatory Science: '541352139'
#- International Policy Network: '522363626'
#- James Madison Institute For Public Policy Studies Inc: '592811908'
#- John Locke Foundation Inc: '561656943'
#- John Templeton Foundation: '621322826'
#- John William Pope Foundation: '581691765'
#- Kern Family Foundation: '391923558'
#- Kiewit Mining Group Inc: '476098282'
#- Kiewit Mining Group Inc: '476029996'
#- Kinder Morgan Inc: '841148161'
#- Knowledge And Progress Fund: '541899251'
#- L'Air Liquide S.A.: '760366343'
#- Lexington Institute: '541880642'
#- Lillian S. Wells Foundation, Inc.: '237433827'
#- Lilly Endowment Inc.: '350868122'
#- Locke Institute: '541556624'
#- Lockheed Martin Corporation: '475031595'
#- Lockheed Martin Corporation: '136161566'
#- Lynde And Harry Bradley Foundation, Inc. The: '396037928'
#- M.J. Murdock Charitable Trust: '237456468'
#- Mackinac Center: '382701547'
#- Manhattan Institute For Policy Research Inc: '132912529'
#- Marathon Petroleum Corp.: '464439930'
#- Media Research Center Inc: '541429009'
#- Mercatus Center Inc Gwu: '541436224'
#- Mercer Family Foundation: '201982204'
#- MidAmerican Energy Co: '421338550'
#- Mitsubishi Corporation: '133676166'
#- Murphy Oil Corporation: '874000291'
#- NRG Finance Co I LLC: '273283754'
#- National Fuel Gas Company: '201860605'
#- National Grid plc: '113466416'
#- National Mining Association: '521916480'
#- National Petroleum Council: '530182304'
#- National Rural Electric Cooperative Association: '530116145'
#- National Taxpayers Union: '521122683'
#- Nebraska Public Power District: '453689549'
#- "Nestle": '956027479'
#- "Nestle": '956118622'
#- "Nestle": '873568395'
#- NextEra Energy, Inc.: '650031452'
#- NiSource Inc: '510324200'
#- Nissan Motor Co., Ltd.: '954413799'
#- Noble Research Institute, Llc: '730606209'
#- Norfolk Southern: '521328375'
#- OGE Energy Corp: '736093572'
#- ONEOK Inc: '731503823'
#- Oregon Institute Of Science And Medicine: '930814898'
#- Ovintiv Inc: '760663978'
#- PPL Corp: '461605118'
#- PacifiCorp: '943089826'
#- Pacific Research Institute For Public Policy: '942528433'
#- Panasonic Holdings Corp.: '222548639'
#- Pioneer Natural Resources: '752443728'
#- Prometheus Foundation: '271456655'
#- Ramaco Resources Inc: '882516783'
#- Reason Foundation: '953298239'
#- Richard And Barbara Gaby Foundation: '202110682'
#- Richard And Helen Devos Foundation The: '456659303'
#- Roe Foundation The: '237011541'
#- SSAB AB: '201173879'
#- SSAB AB: '412191056'
#- SWEPCO Capital I: '261318214'
#- Sarah Scaife Foundation, Inc.: '251113452'
#- Schwab Charitable: '261997839'
#- Searle Freedom Trust: '367244615'
#- Sempra Infrastructure Partners LP: '261325469'
#- Shelby Cullom Davis Charitable Fund: '203734688'
#- Shell Oil: '136066583'
#- Smith Richardson Foundation: '560611550'
#- TC Energy: '473504335'
#- Texas Public Policy Foundation: '742524057'
#- The AES Corporation: '873898365'
#- The AES Corporation: '820657376'
#- The Southern Company: '582514027'
#- The Southern Company: '582399946'
#- The Williams Companies Inc: '237413843'
#- Thomas Jefferson Institute For Public Policy: '510280185'
#- Thomas W Smith Foundation Inc: '473862135'
#- Toyota Motor Corp.: '953255038'
#- Unilever plc: '136122117'
#- Union Pacific: '136406825'
#- Union Pacific: '800638183'
#- United Airlines: '760691086'
#- United Airlines Holdings, Inc.: '853565514'
#- United For Jobs: '462437321'
#- Valero Energy Corp.: '742904514'
#- Vanguard Charitable Endowment Program: '232888152'
#- Virginia Institute For Public Policy: '541870848'
#- Walton Family Foundation: '133441466'
#- Washington Policy Center: '911752769'
#- William E. Simon Foundation, Inc.: '136217788'
#- William K. Bowes, Jr. Foundation: '943148482'
#- Wisconsin Public Service Corp: '396075016'
#- World Affairs Councils Of America: '521514424'
#- XCEL Energy Inc: '412007734'
- ITOCHU: '845135131'
- Mitsubishi: '521700855'
- Mitsubishi: '330773994'
- Mitsubishi: '383735804'
- Mitsui: '133415220'
- Sumitomo: '202103634'
